### ISSUE TITLE
suggestion: can we have some way to exclude experimental problem at problem list?

### ISSUE THREAD

**Issue by Misuki743** [kenkoooo/AtCoderProblems#1235]
Since most of them have only Japanese problem description, I think it is useful for people don't know Japanese to exclude these problem : )

**Comment by kenkoooo** [comment]
Thank you for using my webapp, and thanks for the suggestion! You can see only the problems of the rated contests from the following link: https://kenkoooo.com/atcoder/#/list/kenkoooo?rated=Only+Rated

Since all the problems of the rated contests have English descriptions, I think that will resolve the issue.
